name: Sample Workflow

on: [push]

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:

    - name: Welcome Message
      run: echo "Welcome Folks"

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: List Files
      run: ls

    - name: Read README.md
      run: cat README.md